# Generated by Django 2.0.5 on 2018-05-14 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('comment_num', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('vector', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.Article')),
            ],
        ),
    ]
