# Generated by Django 2.0.5 on 2018-05-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='author',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='view',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
